### ISSUE TITLE
Genial api

### ISSUE THREAD

**Issue by Krato** [michydev/Covid-19-Spain-API#1]
Tan solo quería agradecerte el desarrollo de la api..

La pienso añadir pronto a mi repositorio: https://github.com/Krato/covid19ESP

Muchas gracias.

**Comment by michyaraque** [comment]
Muchisimas gracias Krato, maravilloso trabajo el de la api global del Covid-19 muchas felicidades para ti tambien, un saludo

**Comment by Krato** [comment]
Solo informarte que ya estoy usando tu api para sacar los últimos registros por ccaa. Gracias de nuevo!

Te he mencionado en el repo: https://github.com/Krato/covid19ESP 

Por cierto, He tenido algún problema con CORS. Lo he solucionado con un proxy aparte, pero por si lo quieres mirar.

Un saludo.

**Comment by Krato** [comment]
Lo dicho, tendrías que aplicar CORS. Es imposible hacer varias peticiones a la api ya que saltan los headers xD

**Comment by michyaraque** [comment]
Listo prueba a ver y me avisas, ya está solventado el tema del CORS, aunque te recomiendo guardar los datos en redis o alguna "base de datos" ya que en sí los datos dados por el gobierno se actualizan cada 24 horas a las 13:00 para ser exactos, muchas gracias un saludo Krato
