### ISSUE TITLE
Error en Madrid

### ISSUE THREAD

**Issue by Krato** [michydev/Covid-19-Spain-API#2]
Hola!

La api no devuelve correctamente los datos de Madrid: https://api.chollx.es/coronavirus/ca/madrid

```
[
  {
    "ccaa": "Madrid",
    "casos_totales": 37584,
    "hospitalizados": 1455,
    "casos_graves": 1,
    "fallecidos": 0,
    "curados": 0,
    "nuevos_respecto_ayer": 0
  }
]
```
Pone fallecidos 0 y curados 0 lo cual es imposible.

Gracias!

**Comment by Krato** [comment]
Vuelvo a comentar.

Pasa con más:

> Castilla La Mancha
> Castilla y León
> C. Valenciana
> Galicia

**Comment by Krato** [comment]
~~Solucionado. Supongo que se habrá solucionado en alguna importación~~

**Comment by michyaraque** [comment]
Al parecer al cambiado el pdf nuevamente en varias partes lo retoco y te aviso, que poco control llevan en el Ministerio de salud

**Comment by Krato** [comment]
> Al parecer al cambiado el pdf nuevamente en varias partes lo retoco y te aviso, que poco control llevan en el Ministerio de salud

Sin duda. Es un caos. 

Muchas gracias. Te paso una imagen de las que se ven mal

<img width="1030" alt="Captura de pantalla 2020-04-05 a las 17 13 56" src="https://user-images.githubusercontent.com/74367/78502352-09e8b480-7761-11ea-9e2c-20cdbcde6b90.png">

**Comment by michyaraque** [comment]
Ha sido resuelto ya, revísalo, 💪🏻 gracias

**Comment by Krato** [comment]
Genial! Muchas gracias
