### ISSUE TITLE
Por qué PDF?

### ISSUE THREAD

**Issue by javieraviles** [michydev/Covid-19-Spain-API#3]
Buenos días,

Una duda que te quería preguntar; por qué lees los datos desde el `PDF`? te da más info o más actualizada? Parecen los mismos datos que sacan por `CSV` ellos mismos en su dashboard:

https://covid19.isciii.es/resources/serie_historica_acumulados.csv

Un saludo!

**Comment by michyaraque** [comment]
Hola Javier, bueno esto se debe a que realicé la Api cuando ellos no tenian ese portal aún, un saludo 👋🏻
