### ISSUE TITLE
Datos no correctos

### ISSUE THREAD

**Issue by Krato** [michydev/Covid-19-Spain-API#4]
Hola de nuevo. 
Creo que algo habrán tocado los del Ministerio pero los datos no son correctos de nuevo.

Gracias

**Comment by michyaraque** [comment]
Hola Krato ¿qué tal? Voy a mirarlo a ver que han hecho

**Comment by michyaraque** [comment]
Listo, se ha resuelto

**Comment by Krato** [comment]
Wow, que rápido.

Sin embargo Cataluña no la saca correctamente.

**Comment by michyaraque** [comment]
Al parecer el nuevo método de obtención de datos que es a través de iscii los datos de Cataluña no están especificados, voy a ver que puedo hacer

**Comment by Krato** [comment]
Anda, no me digas. Jajaja que fuerte. 

Ya me dirás si lo consigues. Gracias
